using Godot;
using System.Collections.Generic;
using System;

public enum DamageType
{
	Flood,
	Wind,
	Secondary
}

internal struct StormState
{
	public float latitude;
	public float longitude;
	public float rotationAngle;
	public List<Node3D> particles;
	public List<Vector2> offsets;
	public float strength;
	public float fadeTimer;
	public float windSpeed;
	public float radius;
	public float range;
	public float windDamageMult;
	public float floodDamageMult;
	public float totalDistanceTraveled;
	public float solarGenerated;
	public Vector2 moveDirection; // Individual storm direction
}

public partial class Storm : Node3D
{
	[Export]
	private Globe _globe;

	// Storm Particle Params
	[Export] public int NumParticles = 750;
	[Export] public float SpiralRadius = 25.0f;
	[Export] public float SpiralTurns = 18.0f;
	[Export] public float EyeRadius = 4.0f;
	[Export] public PackedScene ParticleScene;
	[Export] public float RotationSpeed = 2.0f;

	// Spacing Params for coordinate transformation
	[Export] public float RadPerUnitX = 0.1f;
	[Export] public float RadPerUnitY = 0.1f;

	// Movement Params
	[Export] public float MoveSpeedRadPerSec = 2.0f;

	// Direction indicator component
	[Export] public PackedScene DirectionIndicatorScene;
	private StormDirectionIndicator _directionIndicator;

	// Internal state
	private List<StormState> _storms = [];

	public override void _Ready()
	{
		// Initialize the direction indicator
		if (DirectionIndicatorScene != null)
		{
			_directionIndicator = DirectionIndicatorScene.Instantiate<StormDirectionIndicator>();
		}
		else
		{
			_directionIndicator = new StormDirectionIndicator();
		}

		_directionIndicator.Name = "StormDirectionIndicator";
		_directionIndicator.Globe = _globe;
		AddChild(_directionIndicator);

		// Connect to direction indicator signals
		_directionIndicator.DirectionSet += OnDirectionSet;
	}

	private void OnDirectionSet(Vector2 startLatLon, Vector2 direction)
	{
		SpawnStormAt(startLatLon.X, startLatLon.Y, direction);
	}

	// Get total solar generated by all active storms
	public float GetTotalSolarGenerated()
	{
		float total = 0.0f;
		foreach (var storm in _storms)
		{
			total += storm.solarGenerated;
		}
		return total;
	}

	private void SpawnStormAt(float lat, float lon, Vector2 direction = default)
	{
		if (GameManager.Instance.Solar < 100.0)
		{
			GD.Print("Not enough Solar to spawn a storm!");
			return;
		}

		if (GameManager.Instance.GetRegion(_globe.GetRegionID(new Vector2(lat, lon)))?.Alive == true)
		{
			GD.Print("Cannot spawn storm in a living region!");
			return;
		}

		// Use provided direction or default to right (testing purposes)
		// Should require a direction to be set before spawning
		if (direction == default)
			direction = Vector2.Right;

		// Spawn storm at clicked location and remove Solar cost
		GameManager.Instance.Solar -= 100.0f;

		var stormParticles = new List<Node3D>();
		var initialOffsets = new List<Vector2>();
		float rotationAngle = 0.0f;

		// Get tech tree values for storm properties
		var weatherVars = GameManager.Instance.Game.stormTree.Vars;

		// Calculate storm properties based on tech tree upgrades (base values modified by upgrades)
		float stormRadius = SpiralRadius * weatherVars.Storm.StormRadius;
		float windSpeed = RotationSpeed * weatherVars.Storm.WindSpeed;
		float stormRange = weatherVars.Storm.Range;
		int particleCount = (int)(NumParticles * weatherVars.Storm.StormRadius);

		int spawned = 0;
		int attempts = 0;
		while (spawned < particleCount && attempts < particleCount * 3)
		{
			float t = attempts / particleCount;
			float angle = t * SpiralTurns * Mathf.Tau;
			float radius = t * stormRadius;
			float x = Mathf.Cos(angle) * radius;
			float z = Mathf.Sin(angle) * radius;
			attempts++;

			if (Mathf.Sqrt(x * x + z * z) < EyeRadius)
				continue;

			var instance = ParticleScene.Instantiate<Node3D>();
			instance.Visible = true;
			instance.Position = Vector3.Zero;
			AddChild(instance);

			stormParticles.Add(instance);
			initialOffsets.Add(new Vector2(x, z));
			spawned++;
		}

		var storm = new StormState
		{ 
			latitude = lat,
			longitude = lon,
			rotationAngle = rotationAngle,
			particles = stormParticles,
			offsets = initialOffsets,
			strength = 1.0f, // Full strength
			fadeTimer = 0.0f, // No fade initially
			windSpeed = windSpeed, // Store calculated wind speed
			radius = stormRadius, // Store calculated radius
			range = stormRange, // Store calculated range
			windDamageMult = weatherVars.Storm.WindDamage, // Wind damage multiplier
			floodDamageMult = weatherVars.Storm.FloodDamage, // Flood damage multiplier
			totalDistanceTraveled = 0.0f, // Track distance for range limit
			solarGenerated = 0.0f, // Track solar generated by this storm
			moveDirection = direction.Normalized() // Individual storm direction
		};

		_storms.Add(storm);

		if (GameManager.Instance.PrintDebug)
		{
			GD.Print($"[Storm] Spawned storm with radius: {stormRadius:F1}, wind speed: {windSpeed:F1}, range: {stormRange:F1}, direction: ({direction.X:F2}, {direction.Y:F2})");
		}
	}

	public override void _Process(double delta)
	{
		var FPS = Engine.GetFramesPerSecond();
		GetTree().Root.Title = $"Storms: {_storms.Count} | FPS: {FPS}";

		var stormsToRemove = new List<int>();

		for (int stormIdx = 0; stormIdx < _storms.Count; stormIdx++)
		{
			var storm = _storms[stormIdx];

			float stormWindSpeed = storm.windSpeed;
			float rotationAngle = storm.rotationAngle + stormWindSpeed * (float)delta;
			storm.rotationAngle = rotationAngle;

			float originLat = storm.latitude;
			float originLon = storm.longitude;

			Vector2 stormDirection = storm.moveDirection;
			var moveDelta = stormDirection * MoveSpeedRadPerSec * (float)delta;
			originLon += moveDelta.X;
			originLat += moveDelta.Y;

			// Update distance traveled and check range limit
			float distanceDelta = moveDelta.Length();
			float totalDistance = storm.totalDistanceTraveled + distanceDelta;
			storm.totalDistanceTraveled = totalDistance;
			float stormRange = storm.range;

			float depletion = 0.0f;             // Reduce strength based on distance traveled (storms weaken over distance) and latitude
			depletion += totalDistance > stormRange ? 0.35f : 0.0f;
			depletion += Mathf.Abs(originLat) * 2.0f / Mathf.Pi;

			storm.latitude = originLat;
			storm.longitude = originLon;

			var particles = storm.particles;
			var offsets = storm.offsets;

			// --- Storm strength and fading ---
			float strength = storm.strength;
			if (strength < 0.2f)
			{
				// Some fade effect will need to be applied/created

				float fade_timer = storm.fadeTimer;
				fade_timer += (float)delta;
				storm.fadeTimer = fade_timer;
				float fade = Mathf.Clamp(1.0f - fade_timer / 2.0f, 0.0f, 1.0f); // 2 seconds fade

				// Delete particles if fade is complete
				if (fade <= 0.0f)
				{
					foreach (var p in particles)
						if (IsInstanceValid(p)) p.QueueFree();
					stormsToRemove.Add(stormIdx);

					// Log final stats for this storm
					float totalSolar = storm.solarGenerated;
					if (GameManager.Instance.PrintDebug && totalSolar > 0)
					{
						GD.Print($"[Storm] Storm completed. Total Solar generated: {totalSolar:F1}");
					}
					// Save changes to struct before continue
					_storms[stormIdx] = storm;
					continue;
				}
			}

			// --- Particle positioning ---
			for (int i = 0; i < particles.Count; i++)
			{
				var offset = offsets[i].Rotated(rotationAngle);
				float lat = originLat + offset.Y * RadPerUnitY;
				float lon = originLon + offset.X * RadPerUnitX / Mathf.Cos(lat);
				var globePoint = _globe.GetSurfacePoint(new(lat, lon));
				particles[i].GlobalPosition = 1.025f * (globePoint.Position - _globe.Position) + _globe.Position;
			}


			int regionID = _globe.GetRegionID(new(originLat, originLon));
			var region = GameManager.Instance.GetRegion(regionID);
			if (region != null && region.Alive)
			{
				// Get storm-specific damage multipliers
				float windDamageMult = storm.windDamageMult;
				float floodDamageMult = storm.floodDamageMult;
				float stormRadius = storm.radius;

				float baseDamagePerSecond = 0.3f;

				float radiusMultiplier = Mathf.Pow(stormRadius / SpiralRadius, 1.5f);
				float strengthMultiplier = Mathf.Pow(strength, 1.2f);

				// Calculate damage based on multipliers (flood/secondary damage is reduced compared to wind)
				float windDamage = baseDamagePerSecond * windDamageMult * radiusMultiplier * strengthMultiplier;
				float floodDamage = baseDamagePerSecond * floodDamageMult * radiusMultiplier * strengthMultiplier * 0.5f;
				float secondaryDamage = baseDamagePerSecond * radiusMultiplier * strengthMultiplier * 0.25f; // Infrastructure damage

				// Apply damage to region
				GameManager.Instance.ApplyDamage(regionID, (float)(windDamage * delta), DamageType.Wind);
				GameManager.Instance.ApplyDamage(regionID, (float)(floodDamage * delta), DamageType.Flood);
				GameManager.Instance.ApplyDamage(regionID, (float)(secondaryDamage * delta), DamageType.Secondary);

				// Storms decrease in strength as they travel over land
				float totalDamage = windDamage + floodDamage + secondaryDamage;
				float solarGenerated = (float)(CalculateSolarFromDamage(totalDamage, strength, regionID, windDamageMult, floodDamageMult, radiusMultiplier) * delta);

				if (solarGenerated > 0)
				{
					GameManager.Instance.Solar += solarGenerated;
					storm.solarGenerated += solarGenerated;
				}
			}
			else
			{
				// We are over the ocean
				depletion -= 0.1f;
			}

			// GD.Print($"Storm at ({totalDistance:F2}m) | Range: {stormRange:F2}");
			// GD.Print($"Depletion {depletion:F2} | Strength {strength:F2}");
			strength -= depletion * (float)delta; // Base deplete rate + range depletion
			if (strength < 0.0f)
				strength = 0.0f;
			storm.strength = strength;

			// Save changes to struct back to the list
			_storms[stormIdx] = storm;
		}

		// Remove storms by index in reverse order to avoid shifting issues
		stormsToRemove.Sort((a, b) => b.CompareTo(a));
		foreach (var idx in stormsToRemove)
			_storms.RemoveAt(idx);
	}

	private float CalculateSolarFromDamage(float damage, float stormStrength, int regionID, float windMult, float floodMult, float radiusMult)
	{
		float baseSolarRate = damage * 100.0f;
		float strengthBonus = Mathf.Pow(stormStrength, 1.2f) * 1.5f;

		// Arbirtrary multipliers based on tech tree upgrades (by feel...)
		float techTreeBonus = 0.0f;
		techTreeBonus += (windMult - 1.0f) * 1.5f;
		techTreeBonus += (floodMult - 1.0f) * 1.25f;
		techTreeBonus += (radiusMult - 1.0f) * 2.0f;

		float regionMultiplier = 1.0f;
		if (regionID >= 0 && regionID <= GameManager.Instance.Game.RegionAIs.Length)
		{
			var regionAI = GameManager.Instance.Game.RegionAIs[regionID];
			regionMultiplier = 0.5f + (regionAI.regionStats.developmentIndex * 1.5f);
		}

		float populationBonus = 0.0f;
		if (regionID >= 0 && regionID <= GameManager.Instance.Game.RegionAIs.Length)
		{
			var regionAI = GameManager.Instance.Game.RegionAIs[regionID];
			float popFactor = Math.Min(regionAI.regionStats.population / 100.0f, 5.0f); // Scaling bonus (needs work. Has a cap at 5x)
			populationBonus = popFactor * 0.5f;
		}

		float finalSolar = 0.25f * (baseSolarRate + strengthBonus + techTreeBonus + populationBonus) * regionMultiplier;

		/*
		// Variance in generation
		float randomVariation = Random.Shared.Nextfloat() * 0.2 - 0.1; // ±10% variation
		finalSolar *= (1.0 + randomVariation);
		*/

		return finalSolar;
	}

}
