using Godot;
using System.Collections.Generic;
using System;

public enum DamageType
{
	Flood,
	Wind,
	Secondary
}

public partial class Storm : Node3D
{
	[Export]
	private Globe _globe;

	// Storm Particle Params
	[Export] public int NumParticles = 750;
	[Export] public float SpiralRadius = 25.0f;
	[Export] public float SpiralTurns = 18.0f;
	[Export] public float EyeRadius = 4.0f;
	[Export] public PackedScene ParticleScene;
	[Export] public float RotationSpeed = 2.0f;

	// Spacing Params for coordinate transformation
	[Export] public float RadPerUnitX = 0.1f;
	[Export] public float RadPerUnitY = 0.1f;

	// Movement Params
	[Export] public float MoveSpeedRadPerSec = 2.0f;

	// Direction indicator component
	[Export] public PackedScene DirectionIndicatorScene;
	private StormDirectionIndicator _directionIndicator;

	// Internal state
	private List<Dictionary<string, object>> storms = new List<Dictionary<string, object>>();
	
	// Tutorial mode
	public bool IsTutorialMode = false; 

	public override void _Ready()
	{
		// Initialize the direction indicator
		if (DirectionIndicatorScene != null)
		{
			_directionIndicator = DirectionIndicatorScene.Instantiate<StormDirectionIndicator>();
		}
		else
		{
			_directionIndicator = new StormDirectionIndicator();
		}
		
		_directionIndicator.Name = "StormDirectionIndicator";
		_directionIndicator.Globe = _globe;
		AddChild(_directionIndicator);
		
		// Connect to direction indicator signals
		_directionIndicator.DirectionSet += OnDirectionSet;
	}

	private void OnDirectionSet(Vector2 startLatLon, Vector2 direction)
	{
		// Block storm spawning during tutorial
		if (IsTutorialMode)
		return; 
		
		SpawnStormAt(startLatLon.X, startLatLon.Y, direction);
	}
	
	// Get total solar generated by all active storms
	public double GetTotalSolarGenerated()
	{
		double total = 0;
		foreach (var storm in storms)
		{
			total += (double)storm["total_solar_generated"];
		}
		return total;
	}

	private void SpawnStormAt(float lat, float lon, Vector2 direction = default)
	{
		if (GameManager.Instance.Solar < 100.0)
		{
			GD.Print("Not enough Solar to spawn a storm!");
			return;
		}

		if (GameManager.Instance.GetRegion(_globe.GetRegionID(new Vector2(lat, lon)))?.Alive == true)
		{
			GD.Print("Cannot spawn storm in a living region!");
			return;
		}

		// Use provided direction or default to right (testing purposes)
		// Should require a direction to be set before spawning
		if (direction == default)
			direction = Vector2.Right;

		// Spawn storm at clicked location and remove Solar cost
		GameManager.Instance.Solar -= 100.0;

		var stormParticles = new List<Node3D>();
		var initialOffsets = new List<Vector2>();
		float rotationAngle = 0.0f;

		// Get tech tree values for storm properties
		var weatherVars = GameManager.Instance.Game.stormTree.treeWeather;
		
		// Calculate storm properties based on tech tree upgrades (base values modified by upgrades)
		float stormRadius = SpiralRadius * (weatherVars.radius / 100.0f);
		float windSpeed = RotationSpeed * (weatherVars.speed / 100.0f);
		float stormRange = 3.0f * weatherVars.range / 100.0f;
		int particleCount = (int)(NumParticles * (weatherVars.radius / 100.0f));

		int spawned = 0;
		int attempts = 0;
		while (spawned < particleCount && attempts < particleCount * 3)
		{
			float t = (float)attempts / particleCount;
			float angle = t * SpiralTurns * Mathf.Tau;
			float radius = t * stormRadius;
			float x = Mathf.Cos(angle) * radius;
			float z = Mathf.Sin(angle) * radius;
			attempts++;

			if (Mathf.Sqrt(x * x + z * z) < EyeRadius)
				continue;

			var instance = ParticleScene.Instantiate<Node3D>();
			instance.Visible = true;
			instance.Position = Vector3.Zero;
			AddChild(instance);

			stormParticles.Add(instance);
			initialOffsets.Add(new Vector2(x, z));
			spawned++;
		}

		var storm = new Dictionary<string, object>
		{
			{ "origin_lat", lat },
			{ "origin_lon", lon },
			{ "rotation_angle", rotationAngle },
			{ "particles", stormParticles },
			{ "offsets", initialOffsets },
			{ "strength", 1.0f }, // 1.0 = full strength, 0.0 = dead
			{ "fade_timer", 0.0f }, // time since fade started
			{ "wind_speed", windSpeed }, // Store calculated wind speed
			{ "radius", stormRadius }, // Store calculated radius
			{ "range", stormRange }, // Store calculated range
			{ "wind_damage_mult", weatherVars.wind_damage / 100.0f }, // Wind damage multiplier
			{ "flood_damage_mult", weatherVars.flood_damage / 100.0f }, // Flood damage multiplier
			{ "total_distance_traveled", 0.0f }, // Track distance for range limit
			{ "total_solar_generated", 0.0 }, // Track solar generated by this storm
			{ "move_direction", direction.Normalized() }, // Individual storm direction
		};

		storms.Add(storm);
		
		if (GameManager.Instance.PrintDebug)
		{
			GD.Print($"[Storm] Spawned storm with radius: {stormRadius:F1}, wind speed: {windSpeed:F1}, range: {stormRange:F1}, direction: ({direction.X:F2}, {direction.Y:F2})");
		}
	}

	public override void _Process(double delta)
	{
		var FPS = Engine.GetFramesPerSecond();
		GetTree().Root.Title = $"Storms: {storms.Count} | FPS: {FPS}";

		var stormsToRemove = new List<Dictionary<string, object>>();

		foreach (var storm in storms)
		{
			float stormWindSpeed = (float)storm["wind_speed"];
			float rotationAngle = (float)storm["rotation_angle"] + stormWindSpeed * (float)delta;
			storm["rotation_angle"] = rotationAngle;

			float originLat = (float)storm["origin_lat"];
			float originLon = (float)storm["origin_lon"];

			Vector2 stormDirection = (Vector2)storm["move_direction"];
			var moveDelta = stormDirection * MoveSpeedRadPerSec * (float)delta;
			originLon += moveDelta.X;
			originLat += moveDelta.Y;

			// Update distance traveled and check range limit
			float distanceDelta = moveDelta.Length();
			float totalDistance = (float)storm["total_distance_traveled"] + distanceDelta;
			storm["total_distance_traveled"] = totalDistance;
			float stormRange = (float)storm["range"];

			float depletion = 0.0f;				// Reduce strength based on distance traveled (storms weaken over distance) and latitude
			depletion += totalDistance > stormRange ? 0.35f : 0.0f;
			depletion += Mathf.Abs(originLat) * 2.0f / Mathf.Pi;

			storm["origin_lat"] = originLat;
			storm["origin_lon"] = originLon;

			var particles = (List<Node3D>)storm["particles"];
			var offsets = (List<Vector2>)storm["offsets"];

			// --- Storm strength and fading ---
			float strength = (float)storm["strength"];
			if (strength < 0.2f)
			{
				// Some fade effect will need to be applied/created

				float fade_timer = (float)storm["fade_timer"];
				fade_timer += (float)delta;
				storm["fade_timer"] = fade_timer;
				float fade = Mathf.Clamp(1.0f - fade_timer / 2.0f, 0.0f, 1.0f); // 2 seconds fade

				// Delete particles if fade is complete
				if (fade <= 0.0f)
				{
					foreach (var p in particles)
						if (IsInstanceValid(p)) p.QueueFree();
					stormsToRemove.Add(storm);

					// Log final stats for this storm
					double totalSolar = (double)storm["total_solar_generated"];
					if (GameManager.Instance.PrintDebug && totalSolar > 0)
					{
						GD.Print($"[Storm] Storm completed. Total Solar generated: {totalSolar:F1}");
					}
					continue;
				}
			}

			// --- Particle positioning ---
			for (int i = 0; i < particles.Count; i++)
			{
				var offset = offsets[i].Rotated(rotationAngle);
				float lat = originLat + offset.Y * RadPerUnitY;
				float lon = originLon + offset.X * RadPerUnitX / Mathf.Cos(lat);
				var globePoint = _globe.GetSurfacePoint(new(lat, lon));
				particles[i].GlobalPosition = 1.025f * (globePoint.Position - _globe.Position) + _globe.Position;
			}


			int regionID = _globe.GetRegionID(new(originLat, originLon));
			var region = GameManager.Instance.GetRegion(regionID);
			if (region != null && region.Alive)
			{
				// Get storm-specific damage multipliers
				float windDamageMult = (float)storm["wind_damage_mult"];
				float floodDamageMult = (float)storm["flood_damage_mult"];
				float stormRadius = (float)storm["radius"];

				double baseDamagePerSecond = 0.3f;

				double radiusMultiplier = Math.Pow(stormRadius / SpiralRadius, 1.5);
				double strengthMultiplier = Math.Pow(strength, 1.2);

				// Calculate damage based on multipliers (flood/secondary damage is reduced compared to wind)
				double windDamage = baseDamagePerSecond * windDamageMult * radiusMultiplier * strengthMultiplier;
				double floodDamage = baseDamagePerSecond * floodDamageMult * radiusMultiplier * strengthMultiplier * 0.5;
				double secondaryDamage = baseDamagePerSecond * radiusMultiplier * strengthMultiplier * 0.25; // Infrastructure damage

				// Apply damage to region
				GameManager.Instance.ApplyDamage(regionID, windDamage * delta, DamageType.Wind);
				GameManager.Instance.ApplyDamage(regionID, floodDamage * delta, DamageType.Flood);
				GameManager.Instance.ApplyDamage(regionID, secondaryDamage * delta, DamageType.Secondary);

				// Storms decrease in strength as they travel over land
				double totalDamage = windDamage + floodDamage + secondaryDamage;
				double solarGenerated = CalculateSolarFromDamage(totalDamage, strength, regionID, windDamageMult, floodDamageMult, radiusMultiplier) * delta;

				if (solarGenerated > 0)
				{
					GameManager.Instance.Solar += solarGenerated;
					storm["total_solar_generated"] = (double)storm["total_solar_generated"] + solarGenerated;
				}
			}
			else
			{
				// We are over the ocean
				depletion -= 0.1f;
			}

			// GD.Print($"Storm at ({totalDistance:F2}m) | Range: {stormRange:F2}");
			// GD.Print($"Depletion {depletion:F2} | Strength {strength:F2}");
			strength -= depletion * (float)delta; // Base deplete rate + range depletion
			if (strength < 0.0f)
				strength = 0.0f;
			storm["strength"] = strength;
		}

		foreach (var s in stormsToRemove)
			storms.Remove(s);
	}

	private double CalculateSolarFromDamage(double damage, float stormStrength, int regionID, float windMult, float floodMult, double radiusMult)
	{
		double baseSolarRate = damage * 100.0; 
		double strengthBonus = Math.Pow(stormStrength, 1.2) * 1.5;

		// Arbirtrary multipliers based on tech tree upgrades (by feel...)
		double techTreeBonus = 0.0;
		techTreeBonus += (windMult - 1.0) * 1.5;
		techTreeBonus += (floodMult - 1.0) * 1.25;
		techTreeBonus += (radiusMult - 1.0) * 2.0; 

		double regionMultiplier = 1.0;
		if (regionID >= 0 && regionID <= GameManager.Instance.Game.RegionAIs.Length)
		{
			var regionAI = GameManager.Instance.Game.RegionAIs[regionID];
			regionMultiplier = 0.5 + (regionAI.regionStats.developmentIndex * 1.5);
		}

		double populationBonus = 0.0;
		if (regionID >= 0 && regionID <= GameManager.Instance.Game.RegionAIs.Length)
		{
			var regionAI = GameManager.Instance.Game.RegionAIs[regionID];
			double popFactor = Math.Min(regionAI.regionStats.population / 100.0, 5.0); // Scaling bonus (needs work. Has a cap at 5x)
			populationBonus = popFactor * 0.5;
		}

		double finalSolar = 0.25 * (baseSolarRate + strengthBonus + techTreeBonus + populationBonus) * regionMultiplier;

		/*
		// Variance in generation
		double randomVariation = Random.Shared.NextDouble() * 0.2 - 0.1; // ±10% variation
		finalSolar *= (1.0 + randomVariation);
		*/

		return finalSolar;
	}
	
}
