using Godot;
using System.Collections.Generic;
using System;

public enum DamageType
{
	Flood,
	Wind,
	Secondary
}

internal struct StormState
{
	public Vector2 postition;
	public float rotationAngle;
	public List<Node3D> particles;
	public List<Vector2> offsets;
	public float strength;
	public float fadeTimer;
	public float windSpeed;
	public float radius;
	public float range;
	public float windDamageMult;
	public float floodDamageMult;
	public float totalDistanceTraveled;
	public float solarGenerated;
	public Vector2 moveDirection; // Individual storm direction
}

public partial class Storm : Node3D
{
	[Export]
	private Globe _globe;

	// Storm Particle Params
	[Export] public float ParticleDensity = 0.2f;
	[Export] public float ParticleSize = 0.04f;
	[Export] public float SpiralTurns = 6.0f;
	[Export] public float EyeRadius = 4.0f;
	[Export] public PackedScene ParticleScene;
	[Export] public float RotationSpeed = 2.0f;


	// Movement Params
	[Export] public float MoveSpeedRadPerSec = 2.0f;

	// Direction indicator component
	[Export] public PackedScene DirectionIndicatorScene;
	private StormDirectionIndicator _directionIndicator;

	// Internal state
	private List<StormState> _storms = [];

	// Tutorial mode
	public bool IsTutorialMode = false; 

	public override void _Ready()
	{
		// Initialize the direction indicator
		if (DirectionIndicatorScene != null)
		{
			_directionIndicator = DirectionIndicatorScene.Instantiate<StormDirectionIndicator>();
		}
		else
		{
			_directionIndicator = new StormDirectionIndicator();
		}

		_directionIndicator.Name = "StormDirectionIndicator";
		_directionIndicator.Globe = _globe;
		AddChild(_directionIndicator);

		// Connect to direction indicator signals
		_directionIndicator.DirectionSet += OnDirectionSet;
	}

	private void OnDirectionSet(Vector2 startLatLon, Vector2 direction)
	{
		// Block storm spawning during tutorial
		if (IsTutorialMode)
		return; 
		
		SpawnStormAt(startLatLon.X, startLatLon.Y, direction);
	}

	// Get total solar generated by all active storms
	public float GetTotalSolarGenerated()
	{
		float total = 0.0f;
		foreach (var storm in _storms)
		{
			total += storm.solarGenerated;
		}
		return total;
	}

	private void SpawnStormAt(float lat, float lon, Vector2 direction = default)
	{
		if (GameManager.Instance.Solar < 100.0)
		{
			GD.Print("Not enough Solar to spawn a storm!");
			return;
		}

		if (GameManager.Instance.GetRegion(_globe.GetRegionID(new Vector2(lat, lon)))?.Alive == true)
		{
			GD.Print("Cannot spawn storm in a living region!");
			return;
		}

		// Use provided direction or default to right (testing purposes)
		// Should require a direction to be set before spawning
		if (direction == default)
			direction = Vector2.Right;

		// Spawn storm at clicked location and remove Solar cost
		GameManager.Instance.Solar -= 100.0f;

		var stormParticles = new List<Node3D>();
		var initialOffsets = new List<Vector2>();
		float rotationAngle = 0.0f;

		// Get tech tree values for storm properties
		var stormVars = GameManager.Instance.Game.stormTree.Vars.Storm;

		// Calculate storm properties based on tech tree upgrades (base values modified by upgrades)
		int particleCount = (int)(ParticleDensity * stormVars.Radius * stormVars.Radius);

		for (int i = 0;  i < particleCount; i++)
		{
			float t = (float)i / particleCount;
			float angle = t * SpiralTurns * Mathf.Tau;
			float radius = t * stormVars.Radius;
			float x = Mathf.Cos(angle) * radius;
			float z = Mathf.Sin(angle) * radius;

			if (radius < EyeRadius)
				continue;

			var instance = ParticleScene.Instantiate<Node3D>();
			instance.Visible = true;
			instance.Position = Vector3.Zero;
			instance.Scale = new Vector3(ParticleSize, ParticleSize, ParticleSize) / ParticleDensity; // Scale down particles
			AddChild(instance);

			stormParticles.Add(instance);
			initialOffsets.Add(new Vector2(x, z));
		}

		var storm = new StormState
		{ 
			postition = new(lat, lon),
			rotationAngle = rotationAngle,
			particles = stormParticles,
			offsets = initialOffsets, // in km
			strength = 1.0f, // Full strength
			fadeTimer = 0.0f, // No fade initially
			windSpeed = stormVars.WindSpeed, // Store calculated wind speed
			radius = stormVars.Radius, // Store calculated radius
			range = stormVars.Range, // Store calculated range
			windDamageMult = stormVars.WindDamage, // Wind damage multiplier
			floodDamageMult = stormVars.FloodDamage, // Flood damage multiplier
			totalDistanceTraveled = 0.0f, // Track distance for range limit
			solarGenerated = 0.0f, // Track solar generated by this storm
			moveDirection = direction.Normalized() // Individual storm direction
		};

		_storms.Add(storm);

		if (GameManager.Instance.PrintDebug)
		{
			GD.Print($"[Storm] Spawned storm with radius: {stormVars.Radius:F1}, wind speed: {stormVars.WindSpeed:F1}, range: {stormVars.Range:F1}, direction: ({direction.X:F2}, {direction.Y:F2})");
		}
	}

	public override void _Process(double delta)
	{
		var stormsToRemove = new List<int>();

		for (int stormIdx = 0; stormIdx < _storms.Count; stormIdx++)
		{
			var storm = _storms[stormIdx];
			storm.rotationAngle += RotationSpeed * storm.windSpeed * (float)delta;
			var moveDelta = storm.moveDirection * MoveSpeedRadPerSec * (float)delta;
			float distanceDelta = Utils.HaversineDistance(storm.postition, storm.postition + moveDelta);
			storm.postition += moveDelta;
			storm.totalDistanceTraveled += distanceDelta;

			float depletion = 0.0f;             // Reduce strength based on distance traveled (storms weaken over distance) and latitude
			depletion += storm.totalDistanceTraveled > storm.range ? 0.35f : 0.0f;
			depletion += Mathf.Abs(storm.postition.X) * 2.0f / Mathf.Pi;

			// --- Storm strength and fading ---
			float strength = storm.strength;
			if (strength < 0.2f)
			{
				// Some fade effect will need to be applied/created

				float fade_timer = storm.fadeTimer;
				fade_timer += (float)delta;
				storm.fadeTimer = fade_timer;
				float fade = Mathf.Clamp(1.0f - fade_timer / 2.0f, 0.0f, 1.0f); // 2 seconds fade

				// Delete particles if fade is complete
				if (fade <= 0.0f)
				{
					foreach (var p in storm.particles)
						if (IsInstanceValid(p)) p.QueueFree();
					stormsToRemove.Add(stormIdx);

					// Log final stats for this storm
					float totalSolar = storm.solarGenerated;
					if (GameManager.Instance.PrintDebug && totalSolar > 0)
					{
						GD.Print($"[Storm] Storm completed. Total Solar generated: {totalSolar:F1}");
					}
					// Save changes to struct before continue
					_storms[stormIdx] = storm;
					continue;
				}
			}

			// --- Particle positioning ---
			for (int i = 0; i < storm.particles.Count; i++)
			{
				var offset = storm.offsets[i].Rotated(storm.rotationAngle);
				offset.Y /= Mathf.Cos(storm.postition.X);
				offset /= Utils.EARTH_RADIUS;

				Vector2 latLon = storm.postition + offset;
				var globePoint = _globe.GetSurfacePoint(latLon);
				storm.particles[i].GlobalPosition = 1.025f * (globePoint.Position - _globe.Position) + _globe.Position;
			}

			int regionID = _globe.GetRegionID(storm.postition);
			var region = GameManager.Instance.GetRegion(regionID);
			if (region != null && region.Alive)
			{
				// Get storm-specific damage multipliers
				float windDamageMult = storm.windDamageMult;
				float floodDamageMult = storm.floodDamageMult;
				float stormRadius = storm.radius;

				float baseDamagePerSecond = 0.3f;

				float strengthMultiplier = Mathf.Pow(strength, 1.2f);

				// Calculate damage based on multipliers (flood/secondary damage is reduced compared to wind)
				float windDamage = baseDamagePerSecond * windDamageMult * strengthMultiplier;
				float floodDamage = baseDamagePerSecond * floodDamageMult * strengthMultiplier * 0.5f;
				float secondaryDamage = baseDamagePerSecond * strengthMultiplier * 0.25f; // Infrastructure damage

				// Apply damage to region
				GameManager.Instance.ApplyDamage(regionID, (float)(windDamage * delta), DamageType.Wind);
				GameManager.Instance.ApplyDamage(regionID, (float)(floodDamage * delta), DamageType.Flood);
				GameManager.Instance.ApplyDamage(regionID, (float)(secondaryDamage * delta), DamageType.Secondary);

				// Storms decrease in strength as they travel over land
				float totalDamage = windDamage + floodDamage + secondaryDamage;
				float solarGenerated = (float)(CalculateSolarFromDamage(regionID, strength, windDamage, floodDamage, windDamageMult, floodDamageMult) * delta);

				if (solarGenerated > 0)
				{
					GameManager.Instance.Solar += solarGenerated;
					storm.solarGenerated += solarGenerated;
				}
			}
			else
			{
				// We are over the ocean
				depletion -= 0.1f;
			}

			// GD.Print($"Storm at ({totalDistance:F2}m) | Range: {stormRange:F2}");
			// GD.Print($"Depletion {depletion:F2} | Strength {strength:F2}");
			strength -= depletion * (float)delta; // Base deplete rate + range depletion
			if (strength < 0.0f)
				strength = 0.0f;
			storm.strength = strength;

			// Save changes to struct back to the list
			_storms[stormIdx] = storm;
		}

		// Remove storms by index in reverse order to avoid shifting issues
		stormsToRemove.Sort((a, b) => b.CompareTo(a));
		foreach (var idx in stormsToRemove)
			_storms.RemoveAt(idx);
	}

	private float CalculateSolarFromDamage(int regionID, float strength, float windDamage, float floodDamage, float windMult, float floodMult)
	{
		float baseSolarRate = (windDamage * windMult + floodDamage * floodMult) * 100.0f;
		float strengthBonus = Mathf.Pow(strength, 1.2f) * 1.5f;

		float regionMultiplier = 1.0f;
		if (regionID >= 0 && regionID <= GameManager.Instance.Game.RegionAIs.Length)
		{
			var regionAI = GameManager.Instance.Game.RegionAIs[regionID];
			regionMultiplier = 0.5f + (regionAI.regionStats.developmentIndex * 1.5f);
		}

		float populationBonus = 0.0f;
		if (regionID >= 0 && regionID <= GameManager.Instance.Game.RegionAIs.Length)
		{
			var regionAI = GameManager.Instance.Game.RegionAIs[regionID];
			float popFactor = Math.Min(regionAI.regionStats.population / 100.0f, 5.0f); // Scaling bonus (needs work. Has a cap at 5x)
			populationBonus = popFactor * 0.5f;
		}

		float finalSolar = 0.25f * (baseSolarRate + strengthBonus + populationBonus) * regionMultiplier;

		/*
		// Variance in generation
		float randomVariation = Random.Shared.Nextfloat() * 0.2 - 0.1; // ±10% variation
		finalSolar *= (1.0 + randomVariation);
		*/

		return finalSolar;
	}

}
